sudo: false

dist: xenial

services:
  - xvfb

language: node_js
node_js:
  - stable

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser

branches:
  only:
    - master
